export const CONSTANT_ERROR_HTTP_SESSION = [401, 402, 403];
export const CONSTANT_ERROR_HTTP_SERVER = [500, 501, 502, 503];
export const CONSTANT_ALL_ERROR_HTTP = [
    ...CONSTANT_ERROR_HTTP_SERVER,
    ...CONSTANT_ERROR_HTTP_SESSION,
]